Allow context to be initialised with Any
stencilproject/Stencil pull request #281
Opened 2019-07-17 13:22 UTC by adam-fowler

Given Mirror is being used to serialize objects that are members of the Context dictionary, it only seems logical we shouldn't be limited to initialized a Context with a dictionary. This PR adds the ability to initialize a context with Any

Initialize Context with Any by converting to dictionary
Allow Any to be pushed onto a Context in a similar way
Change Environment functions to use these new functions

2019-07-18 16:37 UTC, adam-fowler commented
This will fix https://github.com/stencilproject/Stencil/issues/223#issuecomment-411833557

2020-01-12 15:20 UTC, ilyapuchka approved these changes

2020-01-12 15:20 UTC, ilyapuchka commented on Tests/StencilTests/TemplateSpec.swift
> +      let result = try template.render(object:[ "name": "Kyle" ])
```suggestion
      let result = try template.render(object: ["name": "Kyle"])
```

2020-01-12 15:20 UTC, ilyapuchka commented on Tests/StencilTests/TemplateSpec.swift
> +        let result = try template.render(object:[ "name": "Kyle" ])
```suggestion
        let result = try template.render(object: ["name": "Kyle"])
```

2020-01-12 15:22 UTC, ilyapuchka commented on Sources/Context.swift
> +  convenience init(object: Any? = nil, environment: Environment? = nil) {
```suggestion
  convenience public init(object: Any? = nil, environment: Environment? = nil) {
```

2020-04-28 15:15 UTC, adam-fowler commented
@ilyapuchka Is this getting merged in or do I need another approval?

2020-08-13 11:48 UTC, djbe requested changes
Can we possibly avoid the `Mirror(...).asDictionary()` bit? Stencil already has quite extensive reflection capabilities for multiple types (when rendering a template).

2020-08-13 11:48 UTC, djbe commented on Sources/Context.swift
> +      return dictionary
Simplify this into 1 line

2020-08-13 17:04 UTC, adam-fowler commented
> Can we possibly avoid the `Mirror(...).asDictionary()` bit? Stencil already has quite extensive reflection capabilities for multiple types (when rendering a template).

I'll have to have a good look at the code again. It was a wee while ago when I wrote this

2020-08-15 17:09 UTC, adam-fowler commented
> Can we possibly avoid the `Mirror(...).asDictionary()` bit? Stencil already has quite extensive reflection capabilities for multiple types (when rendering a template).

@djbe I had a look through the code again. None of the reflection code seems accessible at this point. Is there function that takes an object and converts it to a `[String: Any]` somewhere else?

2026-04-02 17:44 UTC, closed without merging